workflows:
  android-kiosk-build:
    name: 360 Synergy Kiosk Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      android_signing:
        - kiosk_keystore
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: "net.synergy360.kiosk"
        GOOGLE_PLAY_TRACK: internal
      java: 11
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      
      - name: Build Android APK
        script: | 
          ./gradlew assembleRelease
    
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
